# Generated by Django 3.1.14 on 2022-04-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_auth', '0007_auto_20211118_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarpixUserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.IntegerField(choices=[(0, 'Отключить подтверждение пользователя'), (1, 'Подтверждение пользователя до регистрации'), (2, 'Подтверждение пользователя после регистрации')], default=2, verbose_name='Тип подтверждения пользователя при регистрации')),
            ],
            options={
                'verbose_name': 'Настройка регистрации',
                'verbose_name_plural': 'Настройки регистрации',
            },
        ),
    ]
