# Generated by Django 3.2.8 on 2022-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_auth', '0008_garpixuserconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='garpixuserconfig',
            name='min_chars_password',
            field=models.IntegerField(default=2, verbose_name='Минимальное количество букв в пароле'),
        ),
        migrations.AddField(
            model_name='garpixuserconfig',
            name='min_digits_password',
            field=models.IntegerField(default=2, verbose_name='Минимальное количество цифр в пароле'),
        ),
        migrations.AddField(
            model_name='garpixuserconfig',
            name='min_length_password',
            field=models.IntegerField(default=8, verbose_name='Минимальная длина пароля'),
        ),
        migrations.AddField(
            model_name='garpixuserconfig',
            name='min_uppercase_password',
            field=models.IntegerField(default=1, verbose_name='Минимальное количество заглавных букв в пароле'),
        ),
    ]
