# Generated by Django 3.2.10 on 2022-05-06 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220506_0749'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_auth', '0009_auto_20220505_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garpixuserconfig',
            name='registration_type',
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('usersessionmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.usersessionmixin')),
                ('number', models.CharField(blank=True, max_length=256, null=True, verbose_name='user token')),
                ('recognized', models.PositiveIntegerField(choices=[(0, 'Неопознанный'), (1, 'Гость'), (2, 'Зарегистрированный')], default=0, help_text='Обозначает состояние, в котором распознается пользователь.', verbose_name='Тип')),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний вход')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            bases=('user.usersessionmixin', models.Model),
        ),
    ]
