# Generated by Django 3.1.14 on 2022-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0003_auto_20211028_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyconfig',
            name='sms_url',
        ),
        migrations.AddField(
            model_name='notify',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='sms_login',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Логин пользователя СМС провайдера'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='sms_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль для api СМС провайдера'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='sms_url_type',
            field=models.IntegerField(choices=[(0, 'sms.ru'), (1, 'web.szk-info.ru')], default=0, verbose_name='URL СМС провайдера'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='type',
            field=models.IntegerField(choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'Telegram'), (4, 'Viber'), (5, 'System')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='type',
            field=models.IntegerField(choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'Telegram'), (4, 'Viber'), (5, 'System')], verbose_name='Тип'),
        ),
    ]
