# Generated by Django 3.2.16 on 2022-10-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0003_auto_20221021_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(4210, 'Подтверждение номера телефона'), (4211, 'Подтверждение email'), (4212, 'Восстановление пароля'), (4213, 'Подтверждение email по ссылке')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(4210, 'Подтверждение номера телефона'), (4211, 'Подтверждение email'), (4212, 'Восстановление пароля'), (4213, 'Подтверждение email по ссылке')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='systemnotify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(4210, 'Подтверждение номера телефона'), (4211, 'Подтверждение email'), (4212, 'Восстановление пароля'), (4213, 'Подтверждение email по ссылке')], null=True, verbose_name='Событие'),
        ),
    ]
