# Generated by Django 3.2.8 on 2022-05-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0004_auto_20220428_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='notifyconfig',
            name='sms_login',
        ),
        migrations.RemoveField(
            model_name='notifyconfig',
            name='sms_password',
        ),
        migrations.RemoveField(
            model_name='notifyconfig',
            name='sms_url_type',
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='sms_url',
            field=models.CharField(default='http://sms.ru/sms/send', max_length=255, verbose_name='URL СМС провайдера'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='type',
            field=models.IntegerField(choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'Telegram'), (4, 'Viber')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='type',
            field=models.IntegerField(choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'Telegram'), (4, 'Viber')], verbose_name='Тип'),
        ),
    ]
