# Generated by Django 3.2.8 on 2022-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0005_auto_20220504_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(2021, 'Подтверждение номера телефона'), (2022, 'Подтверждение email'), (2023, 'Восстановление пароля по смс'), (2024, 'Восстановление пароля по email'), (2025, 'Подтверждение email по ссылке')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(2021, 'Подтверждение номера телефона'), (2022, 'Подтверждение email'), (2023, 'Восстановление пароля по смс'), (2024, 'Восстановление пароля по email'), (2025, 'Подтверждение email по ссылке')], null=True, verbose_name='Событие'),
        ),
    ]
