# Generated by Django 3.2.19 on 2023-11-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0005_auto_20221103_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(4210, 'Подтверждение номера телефона'), (4211, 'Подтверждение email'), (4212, 'Восстановление пароля по email'), (4213, 'Восстановление пароля по номеру телефона'), (4214, 'Подтверждение email по ссылке'), (4215, 'Уведомление об истечении срока действия пароля')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(4210, 'Подтверждение номера телефона'), (4211, 'Подтверждение email'), (4212, 'Восстановление пароля по email'), (4213, 'Восстановление пароля по номеру телефона'), (4214, 'Подтверждение email по ссылке'), (4215, 'Уведомление об истечении срока действия пароля')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='systemnotify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(4210, 'Подтверждение номера телефона'), (4211, 'Подтверждение email'), (4212, 'Восстановление пароля по email'), (4213, 'Восстановление пароля по номеру телефона'), (4214, 'Подтверждение email по ссылке'), (4215, 'Уведомление об истечении срока действия пароля')], null=True, verbose_name='Событие'),
        ),
    ]
