# Generated by Django 3.2.19 on 2023-11-03 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230510_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='User is blocked'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts_count',
            field=models.IntegerField(default=0, verbose_name='Invalid log in attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='needs_password_update',
            field=models.BooleanField(default=False, verbose_name='Needs password update'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Password last updated date'),
        ),
    ]
