# Generated by Django 3.1.14 on 2022-04-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220428_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='restore_password_confirm_code_email',
            new_name='restore_password_confirm_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restore_password_confirm_code_phone',
        ),
    ]
