# Generated by Django 3.2.23 on 2023-11-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20231103_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_auth_only',
            field=models.BooleanField(default=False, verbose_name='Keycloak auth only'),
        ),
    ]
