# Generated by Django 3.1.14 on 2022-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220428_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_password',
        ),
        migrations.AddField(
            model_name='user',
            name='is_restore_code_confirmed',
            field=models.BooleanField(default=False, verbose_name='Код посстановления подтвержден'),
        ),
        migrations.AddField(
            model_name='user',
            name='restore_date',
            field=models.DateTimeField(null=True, verbose_name='Дата отправки кода восстановления'),
        ),
        migrations.AddField(
            model_name='user',
            name='restore_token',
            field=models.CharField(default='', max_length=40, verbose_name='Токен восстановления пароля'),
        ),
    ]
