# Generated by Django 3.1.14 on 2022-04-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220428_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSessionMixin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_email',
        ),
        migrations.AddField(
            model_name='user',
            name='email_code_send_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_code',
            field=models.CharField(max_length=255, verbose_name='Код подтверждения email'),
        ),
    ]
