# Generated by Django 3.2.8 on 2022-05-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220504_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Токен'),
        ),
    ]
