# Generated by Django 3.2.8 on 2022-05-04 10:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_code_send_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_confirmation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_email',
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='Номер телефона подтвержден'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Новый номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_confirmation_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код подтверждения номера телефона'),
        ),
    ]
