# Generated by Django 3.2.8 on 2022-05-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220504_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_phone_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_confirmation_code',
        ),
        migrations.AddField(
            model_name='user',
            name='email_code_send_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения email'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Новый email'),
        ),
    ]
