# Generated by Django 3.2.10 on 2022-05-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220504_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_confirmed', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('email_confirmation_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения email')),
                ('token', models.CharField(blank=True, max_length=40, null=True, verbose_name='Токен')),
                ('email_code_send_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Новый email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_code_send_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код подтверждения email'),
        ),
    ]
