# Generated by Django 3.2.10 on 2022-05-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220506_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersessionmixin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
