# Generated by Django 3.2.8 on 2022-06-06 07:01

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
            },
        ),
        migrations.CreateModel(
            name='GarpixUserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_length_password', models.IntegerField(default=8, verbose_name='Минимальная длина пароля')),
                ('min_digits_password', models.IntegerField(default=2, verbose_name='Минимальное количество цифр в пароле')),
                ('min_chars_password', models.IntegerField(default=2, verbose_name='Минимальное количество букв в пароле')),
                ('min_uppercase_password', models.IntegerField(default=1, verbose_name='Минимальное количество заглавных букв в пароле')),
            ],
            options={
                'verbose_name': 'Настройка регистрации',
                'verbose_name_plural': 'Настройки регистрации',
            },
        ),
        migrations.CreateModel(
            name='ReferralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Referral way title')),
                ('referral_hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restore_password_confirm_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Restore password code')),
                ('is_restore_code_confirmed', models.BooleanField(default=False, verbose_name='Restore code confirmed')),
                ('restore_date', models.DateTimeField(null=True, verbose_name='Restore code sent date')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone number')),
                ('is_phone_confirmed', models.BooleanField(default=False, verbose_name='Phone number confirmed')),
                ('phone_confirmation_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone confirmation code')),
                ('phone_code_send_date', models.DateTimeField(blank=True, null=True, verbose_name='Code sent date')),
                ('new_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='New phone number')),
                ('is_email_confirmed', models.BooleanField(default=False, verbose_name='Email confirmed')),
                ('email_confirmation_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email confirmation code')),
                ('email_code_send_date', models.DateTimeField(blank=True, null=True, verbose_name='Code sent date')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='New email')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('token_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='user token')),
                ('recognized', models.PositiveIntegerField(choices=[(0, 'Неопознанный'), (1, 'Гость'), (2, 'Зарегистрированный')], default=0, help_text='Обозначает состояние, в котором распознается пользователь.', verbose_name='Тип')),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний вход')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
