# Generated by Django 3.2.8 on 2022-06-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'Пользователь системы', 'verbose_name_plural': 'Пользователи системы'},
        ),
    ]
