# Generated by Django 3.2.16 on 2022-10-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0005_auto_20221021_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='is_restore_code_confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Restore code confirmed'),
        ),
    ]
