# Generated by Django 3.2.16 on 2022-10-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0006_alter_usersession_is_restore_code_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'System user', 'verbose_name_plural': 'System users'},
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='new_email',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='new_phone',
        ),
    ]
