# Generated by Django 3.2.16 on 2022-10-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0007_auto_20221023_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='is_email_confirmed',
            field=models.BooleanField(default=True, verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_phone_confirmed',
            field=models.BooleanField(default=True, verbose_name='Phone number confirmed'),
        ),
    ]
