# Generated by Django 3.2.16 on 2022-10-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0008_auto_20221024_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='Phone number confirmed'),
        ),
    ]
