# Generated by Django 3.2.16 on 2022-10-26 16:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0009_auto_20221026_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='New email'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='new_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='New phone number'),
        ),
    ]
