# Generated by Django 3.2.16 on 2023-01-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0011_auto_20221107_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='restore_by',
            field=models.CharField(choices=[('phone', 'Phone number'), ('email', 'Email')], default='email', max_length=5),
        ),
    ]
