# Generated by Django 3.2.19 on 2023-11-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0015_garpixuserpasswordconfiguration_password_validity_inform_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='garpixuserpasswordconfiguration',
            name='access_token_ttl_seconds',
            field=models.IntegerField(default=0, help_text='0 если ограничение не требуется', verbose_name='Время жизни авторизационного токена'),
        ),
    ]
