# Generated by Django 3.2.19 on 2023-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0016_garpixuserpasswordconfiguration_access_token_ttl_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='garpixuserpasswordconfiguration',
            name='refresh_token_ttl_seconds',
            field=models.IntegerField(default=0, help_text='0 если ограничение не требуется', verbose_name='Время жизни рефреш токена'),
        ),
    ]
