# Generated by Django 3.2.23 on 2024-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0017_garpixuserpasswordconfiguration_refresh_token_ttl_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='garpixuserpasswordconfiguration',
            name='access_tokens_count',
            field=models.IntegerField(default=-1, help_text='-1 если отправка уведомлений не требуется', verbose_name='Количество хранимых access-токенов (самый старый будет удален)'),
        ),
    ]
