# Generated by Django 4.2 on 2024-03-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0020_alter_garpixuserpasswordconfiguration_access_tokens_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'verbose_name': 'Токен доступа | Access Token', 'verbose_name_plural': 'Токены доступа | Access Tokens'},
        ),
        migrations.AlterModelOptions(
            name='garpixuserpasswordconfiguration',
            options={'verbose_name': 'Настройки безопасности входа | Login Security Settings ', 'verbose_name_plural': 'Настройки безопасности входа | Login Security Settings'},
        ),
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'verbose_name': 'История паролей | Password history', 'verbose_name_plural': 'История паролей | Password history'},
        ),
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'verbose_name': 'Токен обновления доступа | Refresh Token', 'verbose_name_plural': 'Токены обновления доступа | Refresh Tokens'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'Системный пользователь | System user', 'verbose_name_plural': 'Системные пользователи | System users'},
        ),
    ]
